// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNaUUZehcp7y2aD23ZB2aB4kentTOntAA',
    appId: '1:66591065841:web:47f3fd9393603f96784b50',
    messagingSenderId: '66591065841',
    projectId: 'food-app-680d1',
    authDomain: 'food-app-680d1.firebaseapp.com',
    storageBucket: 'food-app-680d1.firebasestorage.app',
    measurementId: 'G-MXC4C6KGZJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa7ITEC2iKPkCrKOGe6M19bHj5pvSr7xw',
    appId: '1:66591065841:android:f176371b46cc1c17784b50',
    messagingSenderId: '66591065841',
    projectId: 'food-app-680d1',
    storageBucket: 'food-app-680d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3TLkbqNHSnVx7HTx1y7rKOIMYCVrmNIU',
    appId: '1:66591065841:ios:fcfbaf1e0a300731784b50',
    messagingSenderId: '66591065841',
    projectId: 'food-app-680d1',
    storageBucket: 'food-app-680d1.firebasestorage.app',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3TLkbqNHSnVx7HTx1y7rKOIMYCVrmNIU',
    appId: '1:66591065841:ios:fcfbaf1e0a300731784b50',
    messagingSenderId: '66591065841',
    projectId: 'food-app-680d1',
    storageBucket: 'food-app-680d1.firebasestorage.app',
    iosBundleId: 'com.example.foodApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNaUUZehcp7y2aD23ZB2aB4kentTOntAA',
    appId: '1:66591065841:web:e692d918d9972d3a784b50',
    messagingSenderId: '66591065841',
    projectId: 'food-app-680d1',
    authDomain: 'food-app-680d1.firebaseapp.com',
    storageBucket: 'food-app-680d1.firebasestorage.app',
    measurementId: 'G-EZQ2TL4X8H',
  );
}
